default_context:
  project_name: 'Cscrub-API'
  project_slug: 'cscrub-api'
  domain_main: 'cscrub-api.willoughbylabs.com'
  domain_staging: 'stag.cscrub-api.willoughbylabs.com'
  docker_swarm_stack_name_main: 'cscrub-api-willoughbylabs-com'
  docker_swarm_stack_name_staging: 'stag-cscrub-api-willoughbylabs-com'
  secret_key: 'a11b94ea6387260ec736e828e2022a10a9413dc0a33117bdb0b780e4695dbb2d'
  first_superuser: 'admin@cscrub-api.willoughbylabs.com'
  first_superuser_password: '1b873d97c5a5a474f5a719d71dc40286856dd2249655247715cd2ee3582e7afa'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.cscrub-api.willoughbylabs.com", "https://stag.cscrub-api.willoughbylabs.com", "https://cscrub-api.willoughbylabs.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@cscrub-api.willoughbylabs.com'
  postgres_password: '1aee5d7c6c96173413f40f29f1887e448102231430705e6d5a7809043e6a59fd'
  pgadmin_default_user: 'admin@cscrub-api.willoughbylabs.com'
  pgadmin_default_user_password: '53a2c75756f088f5a035542c741d94c983248095d8b215b7a65e9cd64880fbba'
  traefik_constraint_tag: 'cscrub-api.willoughbylabs.com'
  traefik_constraint_tag_staging: 'stag.cscrub-api.willoughbylabs.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:9388c973f6d2031d0e8ceb06f4bc7ce7c37c68b036b463fe30cd6f89d3c3d63a'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
